### ISSUE TITLE
Can't find the frontend access address

### ISSUE THREAD

**Issue by theseusyang** [ibagomel/Visual-Flow-frontend#1]
when start up frontend project, Can't find the frontend access address.

**Comment by UladzislauKhizhanok** [comment]
Hi @theseusyang, the default frontend URL is `/`. You can configure it via `BASE_URL` env variable.

**Comment by AGSadovsky** [comment]
I believe, this can be closed. @theseusyang feel free to open another issue if you still experience any problem.
